import "./globals.css";
import { Layout } from "@/components/layout";
import ApolloClientProvider from "@/contexts/apollo";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloClientProvider>
          <Layout>{children}</Layout>
        </ApolloClientProvider>
      </body>
    </html>
  );
}
